-- MySQL Script generated by MySQL Workbench
-- Mon Jun  8 22:56:41 2026
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema deriving_customer_value_an_sql_generated_project
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema deriving_customer_value_an_sql_generated_project
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `deriving_customer_value_an_sql_generated_project` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE deriving_customer_value_an_sql_generated_project ;

-- -----------------------------------------------------
-- Table `deriving_customer_value_an_sql_generated_project`.`products_2nf`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `deriving_customer_value_an_sql_generated_project`.`products_2nf` (
  `Item_ID` INT NOT NULL,
  `Item Purchased` TEXT NULL DEFAULT NULL,
  `Category` TEXT NULL DEFAULT NULL,
  PRIMARY KEY (`Item_ID`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `deriving_customer_value_an_sql_generated_project`.`transactions_2nf`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `deriving_customer_value_an_sql_generated_project`.`transactions_2nf` (
  `Transaction_ID` INT NULL DEFAULT NULL,
  `Customer ID` INT NULL,
  `Item_ID` INT NULL DEFAULT NULL,
  `Purchase Amount (USD)` INT NULL DEFAULT NULL,
  `Season` TEXT NULL DEFAULT NULL,
  `Review Rating` DOUBLE NULL DEFAULT NULL,
  `Shipping Type` TEXT NULL DEFAULT NULL,
  `Discount Applied` INT NULL DEFAULT NULL,
  `Promo Code Used` INT NULL DEFAULT NULL,
  CONSTRAINT FOREIGN KEY (`Item_ID`)
    REFERENCES `deriving_customer_value_an_sql_generated_project`.`products_2nf` 
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `deriving_customer_value_an_sql_generated_project`.`customers_2nf`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `deriving_customer_value_an_sql_generated_project`.`customers_2nf` (
  `Customer ID` INT NOT NULL,
  `Age` INT NULL DEFAULT NULL,
  `Location` TEXT NULL DEFAULT NULL,
  `Subscription Status` INT NULL DEFAULT NULL,
  `Previous Purchases` INT NULL DEFAULT NULL,
  `Frequency of Purchases` TEXT NULL DEFAULT NULL,
  `Avg_no_of_yearly_purchases` INT NULL DEFAULT NULL,
  `Depandancy_Score` DOUBLE NULL DEFAULT NULL,
  `Value` DOUBLE NULL DEFAULT NULL,
  `Satisfaction_flag` TEXT NULL DEFAULT NULL,
  `RFM_Score` INT NULL DEFAULT NULL,
  `Customer_Segment` TEXT NULL DEFAULT NULL,
  PRIMARY KEY (`Customer ID`),
  CONSTRAINT 
    FOREIGN KEY (`Customer ID`)
    REFERENCES `deriving_customer_value_an_sql_generated_project`.`transactions_2nf` 
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `deriving_customer_value_an_sql_generated_project`.`dataset`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `deriving_customer_value_an_sql_generated_project`.`dataset` (
  `ï»¿Customer ID` INT NULL DEFAULT NULL,
  `Age` INT NULL DEFAULT NULL,
  `Gender` TEXT NULL DEFAULT NULL,
  `Item Purchased` TEXT NULL DEFAULT NULL,
  `Category` TEXT NULL DEFAULT NULL,
  `Purchase Amount (USD)` INT NULL DEFAULT NULL,
  `Location` TEXT NULL DEFAULT NULL,
  `Size` TEXT NULL DEFAULT NULL,
  `Color` TEXT NULL DEFAULT NULL,
  `Season` TEXT NULL DEFAULT NULL,
  `Review Rating` DOUBLE NULL DEFAULT NULL,
  `Subscription Status` TEXT NULL DEFAULT NULL,
  `Shipping Type` TEXT NULL DEFAULT NULL,
  `Discount Applied` TEXT NULL DEFAULT NULL,
  `Promo Code Used` TEXT NULL DEFAULT NULL,
  `Previous Purchases` INT NULL DEFAULT NULL,
  `Payment Method` TEXT NULL DEFAULT NULL,
  `Frequency of Purchases` TEXT NULL DEFAULT NULL)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

-- Qn 1 
select avg(`Purchase Amount (USD)`) from dataset as avg_pur_ord;
-- Segment customers into High / Mid / Low by total spend
SELECT
    `Customer ID`,
    SUM(`Purchase Amount (USD)`)                          AS total_spend,
    COUNT(Transaction_ID)                                 AS total_orders,
    ROUND(AVG(`Purchase Amount (USD)`), 2)                AS avg_order_value,
    CASE
        WHEN SUM(`Purchase Amount (USD)`) >= 2000 THEN 'High Value'
        WHEN SUM(`Purchase Amount (USD)`) >= 1000 THEN 'Mid Value'
        ELSE                                             'Low Value'
    END                                                   AS value_segment
FROM transactions_2nf
GROUP BY `Customer ID`;

SELECT
    value_segment,
    COUNT(*)                            AS customers,
    ROUND(AVG(total_spend), 2)          AS avg_spend,
    ROUND(AVG(total_orders), 1)         AS avg_orders,
    ROUND(AVG(c.Age), 1)                AS avg_age,
    c.Location
FROM (
    SELECT
        `Customer ID`,
        SUM(`Purchase Amount (USD)`)    AS total_spend,
        COUNT(Transaction_ID)           AS total_orders,
        CASE
            WHEN SUM(`Purchase Amount (USD)`) >= 2000 THEN 'High Value'
            WHEN SUM(`Purchase Amount (USD)`) >= 1000 THEN 'Mid Value'
            ELSE                                          'Low Value'
        END                             AS value_segment
    FROM transactions_2nf
    GROUP BY `Customer ID`
) AS seg
JOIN customers_2nf c ON seg.`Customer ID` = c.`Customer ID`
GROUP BY value_segment, c.Location
ORDER BY avg_spend DESC;

SELECT
    value_segment,
    COUNT(*)                                AS customers,
    ROUND(AVG(total_spend), 2)              AS avg_total_spend,
    ROUND(AVG(total_orders), 1)             AS avg_orders,
    ROUND(AVG(avg_order_value), 2)          AS avg_order_value,
    ROUND(AVG(promo_used_count), 1)         AS avg_promos_used,
    ROUND(AVG(promo_used_count) /
          NULLIF(AVG(total_orders), 0), 2)  AS promo_dependency_rate
FROM (
    SELECT
        t.`Customer ID`,
        SUM(t.`Purchase Amount (USD)`)      AS total_spend,
        COUNT(t.Transaction_ID)             AS total_orders,
        AVG(t.`Purchase Amount (USD)`)      AS avg_order_value,
        SUM(CASE WHEN t.`Promo Code Used` = 'Yes'
                 OR  t.`Discount Applied` = 'Yes'
                 THEN 1 ELSE 0 END)         AS promo_used_count,
        CASE
            WHEN SUM(t.`Purchase Amount (USD)`) >= 2000 THEN 'High Value'
            WHEN SUM(t.`Purchase Amount (USD)`) >= 1000 THEN 'Mid Value'
            ELSE                                             'Low Value'
        END                                 AS value_segment
    FROM transactions_2nf t
    GROUP BY t.`Customer ID`
) AS seg
GROUP BY value_segment
ORDER BY avg_total_spend DESC;

-- Qn no 2
SELECT
    c.`Customer ID`,
    c.Age,
    c.Location,
    c.`Subscription Status`,
    c.`Frequency of Purchases`,
    COUNT(t.Transaction_ID)                             AS total_orders,
    ROUND(SUM(t.`Purchase Amount (USD)`), 2)            AS total_spend,
    ROUND(AVG(t.`Purchase Amount (USD)`), 2)            AS avg_order_value,
    SUM(CASE WHEN t.`Promo Code Used` = 'Yes'
             OR  t.`Discount Applied` = 'Yes'
             THEN 1 ELSE 0 END)                         AS promo_orders,
    ROUND(SUM(CASE WHEN t.`Promo Code Used` = 'Yes'
                   OR  t.`Discount Applied` = 'Yes'
                   THEN 1 ELSE 0 END)
          / COUNT(t.Transaction_ID) * 100, 1)           AS promo_rate_pct,
    CASE
        WHEN COUNT(t.Transaction_ID) >= 10 THEN 'High Repeat'
        WHEN COUNT(t.Transaction_ID) >= 5  THEN 'Mid Repeat'
        ELSE                                    'Low Repeat'
    END                                                 AS repeat_segment
FROM customers_2nf c
JOIN transactions_2nf t ON c.`Customer ID` = t.`Customer ID`
GROUP BY
    c.`Customer ID`,
    c.Age,
    c.Location,
    c.`Subscription Status`,
    c.`Frequency of Purchases`
HAVING COUNT(t.Transaction_ID) > 1          -- only actual repeat buyers
ORDER BY total_orders DESC, total_spend DESC;
-- Which age group repeats the most?
SELECT
    CASE
        WHEN c.Age BETWEEN 18 AND 25 THEN '18-25'
        WHEN c.Age BETWEEN 26 AND 35 THEN '26-35'
        WHEN c.Age BETWEEN 36 AND 50 THEN '36-50'
        ELSE                               '50+'
    END                                         AS age_group,
    c.`Subscription Status`,
    c.`Frequency of Purchases`,
    COUNT(DISTINCT c.`Customer ID`)             AS customers,
    ROUND(AVG(order_count), 1)                  AS avg_orders,
    ROUND(AVG(total_spend), 2)                  AS avg_spend
FROM customers_2nf c
JOIN (
    SELECT
        `Customer ID`,
        COUNT(Transaction_ID)               AS order_count,
        SUM(`Purchase Amount (USD)`)        AS total_spend
    FROM transactions_2nf
    GROUP BY `Customer ID`
) AS t ON c.`Customer ID` = t.`Customer ID`
GROUP BY age_group,  c.`Subscription Status`, c.`Frequency of Purchases`
ORDER BY avg_orders DESC;

-- Qn no 3

-- ─────────────────────────────────────────────────────────────
-- STEP 1: Classify customers into tenure groups
-- ─────────────────────────────────────────────────────────────
SELECT
    c.`Customer ID`,
    c.`Previous Purchases`,
    CASE
        WHEN c.`Previous Purchases` <= 10 THEN 'Low Tenure'
        WHEN c.`Previous Purchases` <= 25 THEN 'Mid Tenure'
        ELSE                                   'High Tenure'
    END                                             AS tenure_group
FROM customers_2nf c;

-- ─────────────────────────────────────────────────────────────
-- STEP 2: Season × Tenure — which seasons attract new vs loyal?
-- ─────────────────────────────────────────────────────────────
SELECT
    t.Season,
    tenure.tenure_group,
    COUNT(DISTINCT c.`Customer ID`)                 AS customers,
    COUNT(t.Transaction_ID)                         AS total_orders,
    ROUND(AVG(t.`Purchase Amount (USD)`), 2)        AS avg_spend,
    ROUND(AVG(c.`Previous Purchases`), 1)           AS avg_prev_purchases
FROM transactions_2nf t
JOIN customers_2nf c
    ON t.`Customer ID` = c.`Customer ID`
JOIN (
    SELECT
        `Customer ID`,
        CASE
            WHEN `Previous Purchases` <= 10 THEN 'Low Tenure'
            WHEN `Previous Purchases` <= 25 THEN 'Mid Tenure'
            ELSE                                  'High Tenure'
        END AS tenure_group
    FROM customers_2nf
) AS tenure
    ON c.`Customer ID` = tenure.`Customer ID`
GROUP BY t.Season, tenure.tenure_group
ORDER BY t.Season, avg_prev_purchases ASC;

-- ─────────────────────────────────────────────────────────────
-- STEP 3: Category × Tenure — which categories retain vs acquire?
-- ─────────────────────────────────────────────────────────────
SELECT
    p.Category,
    tenure.tenure_group,
    COUNT(DISTINCT c.`Customer ID`)                 AS customers,
    COUNT(t.Transaction_ID)                         AS total_orders,
    ROUND(AVG(t.`Purchase Amount (USD)`), 2)        AS avg_spend,
    ROUND(AVG(c.`Previous Purchases`), 1)           AS avg_prev_purchases,
    ROUND(SUM(CASE WHEN t.`Promo Code Used` = 'Yes'
                   OR  t.`Discount Applied` = 'Yes'
                   THEN 1 ELSE 0 END)
          / COUNT(t.Transaction_ID) * 100, 1)       AS promo_rate_pct
FROM transactions_2nf t
JOIN customers_2nf c
    ON t.`Customer ID` = c.`Customer ID`
JOIN products_2nf p
    ON t.`Item_ID` = p.`Item_ID`             -- ← join key to products
JOIN (
    SELECT
        `Customer ID`,
        CASE
            WHEN `Previous Purchases` <= 10 THEN 'Low Tenure'
            WHEN `Previous Purchases` <= 25 THEN 'Mid Tenure'
            ELSE                                  'High Tenure'
        END AS tenure_group
    FROM customers_2nf
) AS tenure
    ON c.`Customer ID` = tenure.`Customer ID`
GROUP BY p.Category, tenure.tenure_group
ORDER BY p.Category, avg_prev_purchases ASC;

-- QN no 4 and 5

-- ─────────────────────────────────────────────────────────────
-- Geographies: Organic Demand vs Discount-Driven Volume
-- ─────────────────────────────────────────────────────────────
SELECT
    c.Location,
    COUNT(DISTINCT c.`Customer ID`)                     AS total_customers,
    COUNT(t.Transaction_ID)                             AS total_orders,
    ROUND(SUM(t.`Purchase Amount (USD)`), 2)            AS total_revenue,
    ROUND(AVG(t.`Purchase Amount (USD)`), 2)            AS avg_order_value,
    ROUND(AVG(c.`Previous Purchases`), 1)               AS avg_prev_purchases,

    -- Promo-driven orders
    SUM(CASE WHEN t.`Promo Code Used` = 'Yes'
             OR  t.`Discount Applied` = 'Yes'
             THEN 1 ELSE 0 END)                         AS promo_orders,

    -- Organic orders
    SUM(CASE WHEN t.`Promo Code Used` = 'No'
             AND t.`Discount Applied` = 'No'
             THEN 1 ELSE 0 END)                         AS organic_orders,

    -- Promo rate %
    ROUND(SUM(CASE WHEN t.`Promo Code Used` = 'Yes'
                   OR  t.`Discount Applied` = 'Yes'
                   THEN 1 ELSE 0 END)
          / COUNT(t.Transaction_ID) * 100, 1)           AS promo_rate_pct,

    -- Organic rate %
    ROUND(SUM(CASE WHEN t.`Promo Code Used` = 'No'
                   AND t.`Discount Applied` = 'No'
                   THEN 1 ELSE 0 END)
          / COUNT(t.Transaction_ID) * 100, 1)           AS organic_rate_pct,

    -- Organic revenue
    ROUND(SUM(CASE WHEN t.`Promo Code Used` = 'No'
                   AND t.`Discount Applied` = 'No'
                   THEN t.`Purchase Amount (USD)`
                   ELSE 0 END), 2)                      AS organic_revenue,

    -- Signal label
    CASE
        WHEN ROUND(SUM(CASE WHEN t.`Promo Code Used` = 'No'
                            AND t.`Discount Applied` = 'No'
                            THEN 1 ELSE 0 END)
                   / COUNT(t.Transaction_ID) * 100, 1) >= 65
             THEN 'Strong Organic'
        WHEN ROUND(SUM(CASE WHEN t.`Promo Code Used` = 'No'
                            AND t.`Discount Applied` = 'No'
                            THEN 1 ELSE 0 END)
                   / COUNT(t.Transaction_ID) * 100, 1) >= 50
             THEN 'Moderate Organic'
        WHEN ROUND(SUM(CASE WHEN t.`Promo Code Used` = 'No'
                            AND t.`Discount Applied` = 'No'
                            THEN 1 ELSE 0 END)
                   / COUNT(t.Transaction_ID) * 100, 1) >= 35
             THEN 'Mixed'
        ELSE 'Discount Driven'
    END                                                 AS demand_signal

FROM transactions_2nf t
JOIN customers_2nf c
    ON t.`Customer ID` = c.`Customer ID`
GROUP BY c.Location
HAVING COUNT(DISTINCT c.`Customer ID`) >= 10       -- filter out tiny samples
ORDER BY organic_rate_pct DESC, avg_order_value DESC;

